### ISSUE TITLE
 FATAL  Cannot read property 'r' of undefined    

### ISSUE THREAD

**Issue by xxyyzz2050** [medfreeman/nuxt-netlify-cms-module#105]
FATAL  Cannot read property 'r' of undefined                       

  at ModuleContainer.NetlifyCmsModule (node_modules\nuxt-netlify-cms\dist\module.js:294:33)
  at Promise (node_modules\@nuxt\core\dist\core.js:172:30)
  at new Promise (<anonymous>)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:170:12)
  at promise.then (node_modules\@nuxt\common\dist\common.js:1321:43)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
  at startup (internal/bootstrap/node.js:285:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by medfreeman** [comment]
closed in [v4.0.0](https://github.com/medfreeman/nuxt-netlify-cms-module/releases/tag/v4.0.0) release.
