### ISSUE TITLE
this.nuxt.hook is not a function

### ISSUE THREAD

**Issue by razbakov** [medfreeman/nuxt-netlify-cms-module#106]
### Steps to reproduce

- clone repostitory (master branch)
- go to examples folder
- `yarn`
- `yarn dev`

### Expected result

Server running at http://localhost:300

### Actual result

```
$ nuxt
TypeError: this.nuxt.hook is not a function
    at ModuleContainer.NetlifyCmsModule (~/nuxt-netlify-cms-module/example/node_modules/nuxt-netlify-cms/dist/module.js:95:13)
    at ~/nuxt-netlify-cms-module/example/node_modules/nuxt/lib/core/module.js:133:29
    at new Promise (<anonymous>)
    at ModuleContainer._callee2$ (~/nuxt-netlify-cms-module/example/node_modules/nuxt/lib/core/module.js:132:12)
    at tryCatch (~/nuxt-netlify-cms-module/example/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (~/nuxt-netlify-cms-module/example/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (~/nuxt-netlify-cms-module/example/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/nuxt-netlify-cms-module/example/node_modules/nuxt/dist/nuxt.js:954:30)
    at ~/nuxt-netlify-cms-module/example/node_modules/nuxt/dist/nuxt.js:965:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
… debug nuxt › axios › baseURL: /content-api
… debug nuxt › axios › browserBaseURL: /content-api
  nuxt:build App root: ~/nuxt-netlify-cms-module/example +0ms
  nuxt:build Generating ~/nuxt-netlify-cms-module/example/.nuxt files... +0ms
  nuxt:build Generating files... +73ms
  nuxt:build Generating routes... +1ms
  nuxt:build Building files... +25ms
  nuxt:build Adding webpack middleware... +85ms
Build completed in 5.094s

 DONE  Compiled successfully in 5097ms                                  11:13:58

 OPEN  http://localhost:3000
```

http://localhost:3000 shows error "Cannot GET /"

**Comment by medfreeman** [comment]
closed in [v4.0.0](https://github.com/medfreeman/nuxt-netlify-cms-module/releases/tag/v4.0.0) release.
